{"uid":"e5ee46a3ed272cbd","name":"test_formSubmission[getData0]","fullName":"tests.rahult.test_HomePage.TestHomePage#test_formSubmission","time":{"start":1687766697146,"stop":1687766697146,"duration":0},"status":"skipped","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"setup","time":{"start":1687766697147,"stop":1687766698643,"duration":1496},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x562f6544d4e3 <unknown>\n#1 0x562f6517cc76 <unknown>\n#2 0x562f651a5d78 <unknown>\n#3 0x562f651a2029 <unknown>\n#4 0x562f651e0ccc <unknown>\n#5 0x562f651e047f <unknown>\n#6 0x562f651d7de3 <unknown>\n#7 0x562f651ad2dd <unknown>\n#8 0x562f651ae34e <unknown>\n#9 0x562f6540d3e4 <unknown>\n#10 0x562f654113d7 <unknown>\n#11 0x562f6541bb20 <unknown>\n#12 0x562f65412023 <unknown>\n#13 0x562f653e01aa <unknown>\n#14 0x562f654366b8 <unknown>\n#15 0x562f65436847 <unknown>\n#16 0x562f65446243 <unknown>\n#17 0x7fb5e7ad2b43 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/python_selenium_test/python_selenium_test/tests/conftest.py\", line 29, in setup\n    driver = webdriver.Chrome(\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 84, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 104, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"afterStages":[],"labels":[{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"getData","value":"{'firstname': 'der', 'lastname': 'efg', 'email': 'f@email.com', 'gender': 'Female'}"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","categories":[],"tags":[]},"source":"e5ee46a3ed272cbd.json","parameterValues":["{'firstname': 'der', 'lastname': 'efg', 'email': 'f@email.com', 'gender': 'Female'}"]}