{"uid":"f720ae67c1457c8c","name":"test_e2e","fullName":"tests.rahult.test_e2e.TestOne#test_e2e","time":{"start":1687766697146,"stop":1687766697146,"duration":0},"status":"skipped","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"setup","time":{"start":1687766697147,"stop":1687766698640,"duration":1493},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55e347d094e3 <unknown>\n#1 0x55e347a38c76 <unknown>\n#2 0x55e347a61d78 <unknown>\n#3 0x55e347a5e029 <unknown>\n#4 0x55e347a9cccc <unknown>\n#5 0x55e347a9c47f <unknown>\n#6 0x55e347a93de3 <unknown>\n#7 0x55e347a692dd <unknown>\n#8 0x55e347a6a34e <unknown>\n#9 0x55e347cc93e4 <unknown>\n#10 0x55e347ccd3d7 <unknown>\n#11 0x55e347cd7b20 <unknown>\n#12 0x55e347cce023 <unknown>\n#13 0x55e347c9c1aa <unknown>\n#14 0x55e347cf26b8 <unknown>\n#15 0x55e347cf2847 <unknown>\n#16 0x55e347d02243 <unknown>\n#17 0x7fd248d29b43 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/python_selenium_test/python_selenium_test/tests/conftest.py\", line 29, in setup\n    driver = webdriver.Chrome(\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 84, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 104, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"afterStages":[],"labels":[{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","categories":[],"tags":[]},"source":"f720ae67c1457c8c.json","parameterValues":[]}